apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kds-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/zncdatadev/catalog:latest
  displayName: kds catalog
  publisher: zncdata-labs
  updateStrategy:
    registryPoll:
      interval: 5m